### PR TITLE
Fix parameter types

### PR DESCRIPTION
**Pull request by bpar476**

### CODE REVIEW

**Comment by bpar476** [comment]
This is required to pass AWS builds. Also safer customer experience

**Review by theghostwhoforks — APPROVED** [review]
@ddomingorh may be interested in this PR too

**Comment by nanux** [comment]
Is this due to newer version of `cfn-lint` that is used in taskcat 9?

**Review by nanux — APPROVED** [review]

**Comment by bpar476** [comment]
> Is this due to newer version of `cfn-lint` that is used in taskcat 9?

I'm not quite sure of what the full issue is, but it errors out because the type of the default value for "boolean" parameters didn't match the "string" because they were YAML booleans.

**Pull request merged**
