### PR TITLE
HTTPS Quality of life improvements

### PR DESCRIPTION
**Pull request by bpar476**
I've modified the load balancer listeners to redirect HTTP traffic to HTTPS if the load balancer has a certificate. I've also removed the TomcatScheme parameter and set it automatically based on if a certificate is present.

There is potentially a reason to keep the TomcatScheme parameter and that's if the customer is deploying the Confluence ALB behind another load balancer which terminates the SSL so it is still an HTTPS connection but the certificate is not on the Confluence ALB.

### CODE REVIEW

**Comment by nanux** [comment]
Doesn't this prevent people to use HTTPs when they are not hosting their certificates in AWS?

It will also require doc changes as the parameter list has changed @ddomingorh

**Comment by bpar476** [comment]
> Doesn't this prevent people to use HTTPs when they are not hosting their certificates in AWS?
> 
> It will also require doc changes as the parameter list has changed @ddomingorh

I don't think there is any way to deploy a certificate to the AWS ALB unless it's stored in Amazon Certificate Manager. How would a customer currently use a certificate that isn't in AWS?

**Comment by bpar476** [comment]
You can also import your certificates into AWS even if they haven't been provisioned by AWS

**Comment by nanux** [comment]
Ok, LGTM. It makes it easier to setup SSL, which is a win.

We should refresh our docs (param was removed), @ddomingorh

**Review by nanux — APPROVED** [review]

**Review by tarka — APPROVED** [review]

**Review by theghostwhoforks — APPROVED** [review]

**Comment by bpar476** [comment]
Just making sure the build passes :)

**Pull request merged**
